import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/About.module.css";
import BeamingCloud from "@/components/BeamingCloud";
import Introduction from "@/components/Introduction";

export default function About() {
  const Intro = () => {
    const introItemOne = (
      <div className={styles.itemOne}>
        <BeamingCloud />
      </div>
    );

    const introItemTwo = (
      <div className={styles.itemTwo}>
        <h1>Tech Stack</h1>
        <div>
          <span>
            <p>React.js</p>
            <Image
              src="/../public/logo/react.png"
              alt="React logo"
              width={500}
              height={500}
            />
          </span>
          <span>
            <p>Next.js</p>
            <Image
              src="/../public/logo/next.png"
              alt="Next logo"
              width={500}
              height={500}
            />
          </span>
          <span>
            <p>Tailwind</p>
            <Image
              src="/../public/logo/tailwindcss.png"
              alt="Tailwind CSS logo"
              width={500}
              height={500}
            />
          </span>
          <span>
            <p>SASS</p>
            <Image
              src="/../public/logo/sass.png"
              alt="SASS logo"
              width={500}
              height={500}
            />
          </span>
        </div>
      </div>
    );

    const introItemThree = (
      <div className={styles.itemThree}>
        <h2>Proficiencies</h2>
        <p>
          Familiar with a variety of programming languages, web technologies,
          and software tools. Committed to using best practices to create
          functional and user-friendly applications. Continuously learning and
          exploring new technologies to further develop my skills and bring
          valuable solutions to the table.
        </p>
      </div>
    );

    return (
      <div className={styles.introduction}>
        <Introduction
          itemOne={introItemOne}
          itemTwo={introItemTwo}
          itemThree={introItemThree}
        />
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Henry Hart | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.about}>
          <Intro />
        </div>
      </main>
    </>
  );
}
