import Head from "next/head";
import styles from "../styles/Archive.module.css";
import Introduction from "@/components/Introduction";
import BeamingCloud from "@/components/BeamingCloud";

export default function Archive() {
  const Intro = () => {
    const introItemOne = (
      <div className={styles.itemOne}>
        <BeamingCloud />
      </div>
    );

    const introItemTwo = (
      <div className={styles.itemTwo}>
        <h1>Previous Iterations</h1>
        <p>
          A curated archive of my personal site's versions, demonstrating the
          growth and development of my digital presence.
        </p>
      </div>
    );

    const introItemThree = (
      <div className={styles.itemThree}>
        <h2>Disclaimer</h2>
        <p>
          While I cannot guarantee the full functionality of all links and
          images within this archive, I cordially invite you to take a leisurely
          stroll down memory lane, and explore the different stages of my
          personal site's development throughout the years.
        </p>
      </div>
    );

    return (
      <div className={styles.introduction}>
        <Introduction
          itemOne={introItemOne}
          itemTwo={introItemTwo}
          itemThree={introItemThree}
        />
      </div>
    );
  };

  const Iterations = () => {
    return (
      <div className={styles.iterations}>
        <div></div>
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Henry Hart | Archive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.archive}>
          <Intro />
          <Iterations />
        </div>
      </main>
    </>
  );
}
