import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Socials from "@/components/Socials";
import styles from "../styles/Home.module.css";

export default function Home() {
  const Introduction = () => {
    const Texts = () => {
      return (
        <>
          <h1>Henry Hart</h1>
          <p>
            A web developer with a passion for creating stunning and
            user-friendly websites.
          </p>
        </>
      );
    };

    const MyResume = () => {
      return (
        <Link className={styles.resume} href="#">
          <p>See my résumé</p>
        </Link>
      );
    };

    return (
      <div className={styles.introduction}>
        <Image
          src="/../public/cloud-w-beaming-smile.png"
          alt="a cloud with a beaming smile"
          width={500}
          height={500}
        />
        <div>
          <Texts />
          <Socials />
          <MyResume />
        </div>
      </div>
    );
  };

  const Projects = () => {
    return <h1>For Projects</h1>;
  };

  return (
    <>
      <Head>
        <title>Henry Hart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.home}>
          <Introduction />
          <Projects />
        </div>
      </main>
    </>
  );
}
