import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Socials from "@/components/Socials";
import styles from "../styles/Home.module.css";

export default function Home() {
  const Introduction = () => {
    return (
      <div className={styles.introduction}>
        {/* intro item 1 */}
        <Image
        className={styles.itemOne}
          src="/../public/cloud-w-beaming-smile.png"
          alt="a cloud with a beaming smile"
          width={500}
          height={500}
        />

        {/* intro item 2 */}
        <div className={styles.itemTwo}>
          <h1>Henry Hart</h1>
          <p>
            A web developer with a passion for creating stunning and
            user-friendly websites.
          </p>
          <Socials />
          <Link href="#">
            <p>See my résumé</p>
          </Link>
        </div>

        {/* intro item 3 */}
        <div className={styles.itemThree}>
          <h2>Bio</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque
            gravida in fermentum et sollicitudin ac orci phasellus egestas.
            Ornare suspendisse sed nisi lacus. Sit amet est placerat in egestas
            erat imperdiet. Vitae purus faucibus ornare suspendisse sed nisi
            lacus sed. Mauris vitae ultricies leo integer malesuada nunc vel
            risus commodo. Vestibulum rhoncus est pellentesque elit ullamcorper.
            Odio ut enim blandit volutpat maecenas. Lobortis feugiat vivamus at
            augue. Ullamcorper dignissim cras tincidunt lobortis feugiat
            vivamus. Vitae congue eu consequat ac felis donec. Fermentum dui
            faucibus in ornare quam viverra. Eget lorem dolor sed viverra ipsum
            nunc. At in tellus integer feugiat scelerisque varius morbi enim
            nunc. Sit amet venenatis urna cursus eget nunc scelerisque viverra
            mauris.
          </p>
        </div>
      </div>
    );
  };

  const Projects = () => {
    const Project = () => {
      return (
        <Link href="#">
          <div>Placeholder for Project</div>
        </Link>
      );
    };

    return (
      <div className={styles.projects}>
        <h2>Projects</h2>
        <Project />
        <Project />
        <Project />
        <Project />
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Henry Hart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.home}>
          <Introduction />
          <Projects />
        </div>
      </main>
    </>
  );
}
